/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AuthLayout: typeof import('./components/templates/AuthLayout.vue')['default']
    AvatarAtom: typeof import('./components/newatom/AvatarAtom.vue')['default']
    ButtonAtom: typeof import('./components/newatom/ButtonAtom.vue')['default']
    DatePickerField: typeof import('./components/atoms/DatePickerField.vue')['default']
    FilterDropdownMolecule: typeof import('./components/molecules/FilterDropdownMolecule.vue')['default']
    FormItem: typeof import('./components/molecules/FormItem.vue')['default']
    Header: typeof import('./components/organisms/Header.vue')['default']
    HeaderAppointment: typeof import('./components/organisms/HeaderAppointment.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputAtom: typeof import('./components/newatom/InputAtom.vue')['default']
    InputField: typeof import('./components/atoms/InputField.vue')['default']
    LoginForm: typeof import('./components/organisms/LoginForm.vue')['default']
    PasswordField: typeof import('./components/atoms/PasswordField.vue')['default']
    RegisterForm: typeof import('./components/organisms/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/atoms/SearchInput.vue')['default']
    SelectField: typeof import('./components/atoms/SelectField.vue')['default']
    Sidebar: typeof import('./components/atoms/Sidebar.vue')['default']
    SubmitButton: typeof import('./components/atoms/SubmitButton.vue')['default']
    Table: typeof import('./components/molecules/Table.vue')['default']
    TableOrganism: typeof import('./components/organisms/TableOrganism.vue')['default']
    TableTemplate: typeof import('./components/templates/TableTemplate.vue')['default']
    UserProfile: typeof import('./components/atoms/UserProfile.vue')['default']
  }
}
