/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    AuthLayout: typeof import('./components/templates/AuthLayout.vue')['default']
    DatePickerField: typeof import('./components/atoms/DatePickerField.vue')['default']
    FormItem: typeof import('./components/molecules/FormItem.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputField: typeof import('./components/atoms/InputField.vue')['default']
    LoginForm: typeof import('./components/organisms/LoginForm.vue')['default']
    PasswordField: typeof import('./components/atoms/PasswordField.vue')['default']
    RegisterForm: typeof import('./components/organisms/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./components/atoms/SelectField.vue')['default']
    SubmitButton: typeof import('./components/atoms/SubmitButton.vue')['default']
  }
}
